<a href="https://colab.research.google.com/github/NohaWaly/convolutional-neural-networks-keras/blob/master/Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
! git clone https://github.com/ardamavi/Sign-Language-Digits-Dataset.git

fatal: destination path 'Sign-Language-Digits-Dataset' already exists and is not an empty directory.


In [0]:
import numpy as np
import matplotlib.pyplot as plt
#cv2 to read image, show and more
import cv2
import os
import random
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from keras import layers
from keras import models as ml
from keras import optimizers
from keras.utils import to_categorical

DataDir = "Sign-Language-Digits-Dataset/Dataset"
ImgSize = 100

Categories = ["0", "1","2","3", "4","5","6", "7","8","9"]
data = []
#iterate over 10 folders
for category in Categories:  
    # create path to each gesture 
    path = os.path.join(DataDir,category) 
    classNum = Categories.index(category)
    #print(path)
    # iterate over each image per each gesture 
    for img in os.listdir(path): 
        print(img)
        # convert to array
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_COLOR) 
        # resize data
        resize_array = cv2.resize(img_array, (ImgSize, ImgSize))
        #append to data
        data.append([resize_array, classNum])
        # graph it
        #plt.imshow(img_array)
        # display!   
        #plt.show()  


IMG_5507.JPG
IMG_5053.JPG
IMG_4564.JPG
IMG_4119.JPG
IMG_4846.JPG
IMG_4745.JPG
IMG_5572.JPG
IMG_4456.JPG
IMG_5816.JPG
IMG_5456.JPG
IMG_4223.JPG
IMG_4338.JPG
IMG_5645.JPG
IMG_5726.JPG
IMG_4786.JPG
IMG_4704.JPG
IMG_5422.JPG
IMG_5111.JPG
IMG_5615.JPG
IMG_4533.JPG
IMG_4049.JPG
IMG_1219.JPG
IMG_5635.JPG
IMG_1260.JPG
IMG_1239.JPG
IMG_4391.JPG
IMG_4807.JPG
IMG_5466.JPG
IMG_5063.JPG
IMG_5007.JPG
IMG_1169.JPG
IMG_4170.JPG
IMG_5786.JPG
IMG_5042.JPG
IMG_4327.JPG
IMG_4684.JPG
IMG_4413.JPG
IMG_4956.JPG
IMG_1118.JPG
IMG_4584.JPG
IMG_4936.JPG
IMG_4203.JPG
IMG_4674.JPG
IMG_5244.JPG
IMG_5736.JPG
IMG_5132.JPG
IMG_4446.JPG
IMG_4109.JPG
IMG_5806.JPG
IMG_5537.JPG
IMG_5183.JPG
IMG_4213.JPG
IMG_4725.JPG
IMG_5517.JPG
IMG_5918.JPG
IMG_4624.JPG
IMG_5370.JPG
IMG_5122.JPG
IMG_5897.JPG
IMG_4466.JPG
IMG_4796.JPG
IMG_4296.JPG
IMG_4946.JPG
IMG_4435.JPG
IMG_5266.JPG
IMG_4370.JPG
IMG_4836.JPG
IMG_5412.JPG
IMG_1179.JPG
IMG_1128.JPG
IMG_5857.JPG
IMG_5193.JPG
IMG_5960.JPG
IMG_5286.JPG
IMG_4403.JPG
IMG_5074.JPG
IMG_4876.JPG

In [0]:
#shuffle data (msh kol class ykon wara b3d)
random.shuffle(data)  
#print(data)


In [0]:
X = []
y = []

for features, label in data:
   X.append(features)
   y.append(label)
#to enter the model it should be np array
X = np.array(X)
y = np.array(y,dtype=int)

#hot incoder
y = to_categorical(y)

print(X)
print(y)

[[[[131 134 138]
   [132 135 139]
   [134 137 141]
   ...
   [118 121 125]
   [116 119 123]
   [115 118 122]]

  [[134 137 141]
   [135 138 142]
   [137 140 144]
   ...
   [120 123 127]
   [118 121 125]
   [116 119 123]]

  [[135 138 142]
   [136 139 143]
   [138 141 145]
   ...
   [121 124 128]
   [119 122 126]
   [117 120 124]]

  ...

  [[133 138 141]
   [134 139 142]
   [134 141 144]
   ...
   [114 119 122]
   [111 116 119]
   [110 115 118]]

  [[131 136 139]
   [132 137 140]
   [131 138 141]
   ...
   [112 117 120]
   [110 115 118]
   [108 113 116]]

  [[129 134 137]
   [130 135 138]
   [130 137 140]
   ...
   [111 116 119]
   [109 114 117]
   [107 112 115]]]


 [[[134 129 128]
   [136 131 130]
   [139 134 133]
   ...
   [124 114 114]
   [122 112 112]
   [121 111 111]]

  [[135 130 129]
   [137 132 131]
   [139 134 133]
   ...
   [125 115 115]
   [123 113 113]
   [122 112 112]]

  [[135 130 129]
   [137 132 131]
   [140 135 134]
   ...
   [126 116 116]
   [124 114 114]
   [123 113

In [0]:
#normalization of data
#get mean of index 3 of shape =>3 layers
mean_array = np.mean(X, axis=3)
print(mean_array.shape)
mean_array = np.expand_dims(mean_array, axis=3)
print(mean_array.shape)
Xnormalized = (X - mean_array)/255.0
print(Xnormalized)

(2062, 100, 100)
(2062, 100, 100, 1)
[[[[-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   ...
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]]

  [[-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   ...
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]]

  [[-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   ...
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]
   [-0.0130719  -0.00130719  0.01437908]]

  ...

  [[-0.01699346  0.00261438  0.01437908]
   [-0.01699346  0.00261438  0.01437908]
   [-0.02222222  0.00522876  0.01699346]
   ...
   [-0.01699346  0.00261438  0.01437908]
   [-0.01699346  0.0

In [0]:
Xnormalized.shape

(2062, 100, 100, 3)

In [0]:
       
#spliting training & test sets
X_train, X_test, y_train, y_test = train_test_split(Xnormalized,y,test_size=0.2, random_state=7)

In [0]:

def create_cnn_model1():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(128, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model2():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(128, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model3():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model4():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
n_split = 4
val_loss = np.zeros(n_split)
val_acc = np.zeros(n_split)

k_Fold = KFold(n_splits=4)
modeling = [create_cnn_model1,create_cnn_model2,create_cnn_model3,create_cnn_model4]
for x in range(4):
  i=0
  for train, validate in k_Fold.split(X_train, y_train):
    model = modeling[x]()
    model.fit(X_train[train], y_train[train], epochs=10)
    val_loss[i], val_acc[i] = model.evaluate(X_train[validate],y_train[validate])
    model.summary()
    i+=1
  print("Average Loss and Accuracy in Architecture" +str(x+1))
  print(val_loss.mean())
  print(val_acc.mean()) 
    #evaluate the testing part
  print("Evaluate testing part")
  model.evaluate(X_test, y_test)
    #get predicted labels
  y_predict = model.predict_classes(X_test)
    #evaluate model using precision, fscore, & recall
  print(classification_report(y_test, y_predict, target_names=Categories))

Epoch 1/10
1236/1236 [==============================] - 18s 15ms/step - loss: 1.7513 - acc: 0.3649
Epoch 2/10
 896/1236 [====================>.........] - ETA: 4s - loss: 0.8101 - acc: 0.7400